#!/usr/bin/env python3
"""
Generate src/qr_vdp.h containing a fully pre-rendered TMS9918 Mode 2
pattern table for the QR screen (QR code + text banner), ready to
blast straight into VRAM at boot with a single vdp_vwrite call.

Layout:
  mod_px=6, 1-module quiet zone (6px each side)
  Total QR footprint: (25+2)*6 = 162px square
  off_x = (256-162)//2 = 47,  off_y = 0
  Text banner at tile rows 20-22 (y=160-183), below the QR.

TMS9918 Mode 2 pattern table: 768 tiles × 8 bytes = 6144 bytes.
Color table: all 0x1F (fg=black, bg=white) — set by vdp_vfill at runtime.
Name table: sequential 0-255 × 3  — set by vdp_vwrite at runtime.
"""

import subprocess, sys, os

URL      = "https://MSX-PICTURE.IRATA.ONLINE/"
FONT_BIN = "/home/thomc/Workspace/fujinet-5cardstud/src/msx/font.bin"

MOD_PX   = 6
QUIET    = 1                              # quiet-zone modules per side
QR_MODS  = 25
QUIET_PX = QUIET * MOD_PX                # 6 px
TOTAL_PX = (QR_MODS + 2 * QUIET) * MOD_PX  # 162 px
OFF_X    = (256 - TOTAL_PX) // 2         # 47
OFF_Y    = 0

INNER_X  = OFF_X + QUIET_PX             # 53 — first active pixel column
INNER_Y  = OFF_Y + QUIET_PX             # 6  — first active pixel row
INNER_W  = QR_MODS * MOD_PX             # 150 px

BANNER   = [
    "SCAN THIS QR CODE TO",   # tile row 20
    "SEND AN IMAGE FROM",     # tile row 21
    "YOUR PHONE!",            # tile row 22
]

# ── QR module matrix ──────────────────────────────────────────────────────────
result = subprocess.run(
    ["qrencode", "-t", "ASCII", "--margin=0", URL],
    capture_output=True, text=True,
)
if result.returncode != 0:
    sys.exit(f"qrencode failed: {result.stderr}")

lines = result.stdout.rstrip('\n').split('\n')
assert len(lines) == QR_MODS and len(lines[0]) == QR_MODS * 2
# qr[row][col] == True  →  dark module
qr = [[lines[r][c * 2] == '#' for c in range(QR_MODS)] for r in range(QR_MODS)]

def is_dark(px, py):
    if px < INNER_X or py < INNER_Y:
        return False
    lx, ly = px - INNER_X, py - INNER_Y
    if lx >= INNER_W or ly >= INNER_W:
        return False
    return qr[ly // MOD_PX][lx // MOD_PX]

# ── Font ──────────────────────────────────────────────────────────────────────
raw        = open(FONT_BIN, "rb").read()
FONT_FIRST = 32
FONT_LAST  = FONT_FIRST + len(raw) // 8 - 1  # 127

def glyph(ch):
    idx = ord(ch) - FONT_FIRST
    return raw[idx * 8 : idx * 8 + 8]

# ── Pre-render full 6144-byte pattern table ───────────────────────────────────
pattern = bytearray(6144)

for tile_idx in range(768):
    tx, ty = tile_idx % 32, tile_idx // 32
    base   = tile_idx * 8

    # Fast skip: tile completely outside the QR active area
    if (tx * 8 + 7 < INNER_X or tx * 8 >= INNER_X + INNER_W or
            ty * 8 + 7 < INNER_Y or ty * 8 >= INNER_Y + INNER_W):
        # pattern bytes stay 0x00 (all-white)
        continue

    for s in range(8):
        py  = ty * 8 + s
        pat = 0
        for b in range(8):
            if is_dark(tx * 8 + b, py):
                pat |= 0x80 >> b
        pattern[base + s] = pat

# Bake text banner into pattern table
for row_idx, line in enumerate(BANNER):
    ty      = 20 + row_idx
    tx_base = (32 - len(line)) // 2
    for col_idx, ch in enumerate(line):
        tile_idx = ty * 32 + tx_base + col_idx
        g = glyph(ch)
        pattern[tile_idx * 8 : tile_idx * 8 + 8] = g

# ── Emit header ───────────────────────────────────────────────────────────────
def hex_array(name, typ, data):
    rows = [f"static const {typ} {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i+16]) + ",")
    rows.append("};")
    return "\n".join(rows)

out = os.path.join(os.path.dirname(__file__), "..", "src", "qr_vdp.h")
with open(out, "w") as f:
    f.write("/* Auto-generated by tools/gen_qr_header.py — DO NOT EDIT */\n")
    f.write(f"/* URL: {URL} */\n\n")
    f.write("#ifndef QR_VDP_H\n#define QR_VDP_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write("/*\n")
    f.write(f" * Pre-rendered TMS9918 Mode 2 pattern table for the QR screen.\n")
    f.write(f" * QR: {QR_MODS}x{QR_MODS} modules, {MOD_PX}px/module, "
            f"offset ({OFF_X},{OFF_Y}), {QUIET}-module quiet zone.\n")
    f.write(f" * Banner rows 20-22: {BANNER}\n")
    f.write(" * Color table (all 0x1F) and name table (sequential) set at runtime.\n")
    f.write(" */\n")
    f.write(hex_array("qr_pattern", "uint8_t", pattern) + "\n\n")
    f.write("#endif /* QR_VDP_H */\n")

dark_count = sum(1 for b in pattern if b)
print(f"Written {out}  ({len(pattern)} bytes, {dark_count} non-zero pattern rows)")
print(f"QR: {QR_MODS}×{QR_MODS} modules, {MOD_PX}px/module, "
      f"offset ({OFF_X},{OFF_Y}), {QUIET}-module quiet zone")
print(f"Banner: {BANNER}")
