#!/usr/bin/env python3
"""
Generate src/qr_vdp.h with compact runtime-rendering data for V9938 SCREEN 7.

Outputs (all ROM-friendly in size):
  qr_palette[4]         - 2-entry V9938 palette: color 0 = white, color 1 = black
  qr_bits[N]            - packed QR module matrix (LSB first), N = ceil(mods²/8)
  QR_MODULES            - module count (macro)
  qr_font[760]          - 95 printable ASCII glyphs × 8 bytes (starting 0x20)
  qr_banner[]           - NULL-terminated array of banner string pointers

SCREEN 7 layout used by main.c:
  MOD_PX=6, QUIET=1, OFF_X=(512-TOTAL_PX)/2, OFF_Y=0
  BANNER_Y = TOTAL_PX + 2  (2-row gap after bottom quiet zone)
"""

import subprocess, sys, os

URL      = "https://msx7-picture.irata.online/"
FONT_BIN = "/home/thomc/Workspace/fujinet-5cardstud/src/msx/font.bin"

BANNER = [
    "SCAN THIS QR CODE TO",
    "SEND AN IMAGE FROM",
    "YOUR PHONE!",
]

# ── QR module matrix ──────────────────────────────────────────────────────────
result = subprocess.run(
    ["qrencode", "-t", "ASCII", "--margin=0", URL],
    capture_output=True, text=True,
)
if result.returncode != 0:
    sys.exit(f"qrencode failed: {result.stderr}")

lines = result.stdout.rstrip("\n").split("\n")
QR_MODS = len(lines)
assert len(lines[0]) == QR_MODS * 2, f"Unexpected QR row width: {len(lines[0])}"

# qr[row][col] == True → dark module
qr = [[lines[r][c * 2] == "#" for c in range(QR_MODS)] for r in range(QR_MODS)]

# Pack into bits (module [row][col] → bit index = row*QR_MODS+col, LSB first)
n_bits  = QR_MODS * QR_MODS
n_bytes = (n_bits + 7) // 8
qr_bytes = bytearray(n_bytes)
for row in range(QR_MODS):
    for col in range(QR_MODS):
        if qr[row][col]:
            bit = row * QR_MODS + col
            qr_bytes[bit >> 3] |= 1 << (bit & 7)

# ── Font ──────────────────────────────────────────────────────────────────────
raw       = open(FONT_BIN, "rb").read()
font_data = raw[0 : 95 * 8]   # glyphs 0x20..0x7E (95 × 8 = 760 bytes)

# ── Verify banner fits on screen ──────────────────────────────────────────────
SCREEN_H = 212
MOD_PX   = 6
QUIET_PX = MOD_PX
TOTAL_PX = (QR_MODS + 2) * MOD_PX
BANNER_Y = TOTAL_PX + 2
banner_end = BANNER_Y + len(BANNER) * 8

if banner_end > SCREEN_H:
    sys.exit(
        f"Banner overflows screen: BANNER_Y={BANNER_Y}, "
        f"end={banner_end}, SCREEN_H={SCREEN_H}"
    )

# ── Helpers ───────────────────────────────────────────────────────────────────
def hex_array(name, typ, data):
    rows = [f"static const {typ} {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i+16]) + ",")
    rows.append("};")
    return "\n".join(rows)

# ── Emit header ───────────────────────────────────────────────────────────────
out = os.path.join(os.path.dirname(__file__), "..", "src", "qr_vdp.h")
with open(out, "w") as f:
    f.write("/* Auto-generated by tools/gen_qr_header.py — DO NOT EDIT */\n")
    f.write(f"/* URL: {URL} */\n\n")
    f.write("#ifndef QR_VDP_H\n#define QR_VDP_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write("/*\n")
    f.write(f" * V9938 SCREEN 7 (GM6) QR screen data for {URL}\n")
    f.write(f" * {QR_MODS}×{QR_MODS} QR modules packed into {n_bytes} bytes (LSB first).\n")
    f.write(f" * Palette: 2 entries (color 0=white, color 1=black).\n")
    f.write(f" * Font: 95 printable ASCII glyphs (0x20-0x7E), 8 bytes each.\n")
    f.write(f" * Banner: {BANNER}\n")
    f.write(f" * Layout: MOD_PX={MOD_PX}, QUIET=1, BANNER_Y={BANNER_Y}\n")
    f.write(" */\n\n")

    # Module count
    f.write(f"#define QR_MODULES {QR_MODS}u\n\n")

    # Palette: color 0=white (R=7,G=7,B=7), color 1=black (R=0,G=0,B=0)
    # V9938 byte0 = 0RRR0BBB = (R<<4)|B, byte1 = 0000 0GGG = G
    pal = [0x77, 0x07, 0x00, 0x00]
    f.write("/* V9938 palette: color 0=white, color 1=black (2 entries × 2 bytes) */\n")
    f.write(hex_array("qr_palette", "uint8_t", pal) + "\n\n")

    f.write(f"/* QR bit matrix: {QR_MODS}×{QR_MODS} modules, LSB-first "
            f"(bit n = module [n/{QR_MODS}][n%{QR_MODS}]) */\n")
    f.write(hex_array("qr_bits", "uint8_t", qr_bytes) + "\n\n")

    f.write("/* ASCII font: 95 glyphs × 8 bytes (glyph 0 = 0x20 space) */\n")
    f.write(hex_array("qr_font", "uint8_t", font_data) + "\n\n")

    f.write("/* Banner strings (NULL-terminated array) */\n")
    f.write("static const char * const qr_banner[] = {\n")
    for line in BANNER:
        f.write(f'    "{line}",\n')
    f.write("    0\n};\n\n")

    f.write("#endif /* QR_VDP_H */\n")

dark = sum(1 for row in qr for m in row if m)
print(f"Written {out}")
print(f"QR: {QR_MODS}×{QR_MODS} modules, {dark} dark, packed into {n_bytes} bytes")
print(f"Layout: TOTAL_PX={TOTAL_PX}, BANNER_Y={BANNER_Y}, banner_end={banner_end}/{SCREEN_H}")
print(f"Font: 95 glyphs × 8 bytes = {len(font_data)} bytes")
